### ISSUE TITLE
generateSalt does not create a 'salt'

### ISSUE THREAD

**Issue by FalcoGer** [BcryptNet/bcrypt.net#26]
The salt for BCrypt is an array of 16 Bytes. The generateSalt function returns a string of 28 or 29 characters, of which 6 or 7 are workfactor and version number and $-delimiters, the rest is the actual salt, base64 encoded.
why you would pass arguments like workfactor or version number to the generatehash function in the form of a string is confusing to me. giving the workfactor to the generatesalt function makes no sense. the generatesalt function doesn't use the workfactor.
So when I saw how to pass a workfactor to the hashing function, I was confused. I expected something like this:

```
String text ="Password"
int workfactor = 13;
string version = "2a";
//
Byte[] salt = BCrypt.GenerateSalt(); // 16B Salt, 87 fa 6f 36 a8 55 c7 df e5 0e ff 55 a3 65 05 89 e2 e0 5e 91 9d 7f
Byte[] hash = BCrypt.GenerateHash(text, salt, workfactor, version); // generates hash, e4 db 21 9f 99 5f 11 b4 09 17 bd 5e 66 0a 7c e8
String digest= BCrypt.GenerateDigest(salt, hash, workfactor, version) // "$2a$13$h/pvNqhVx9/lDv9Vo2UFieLgXpGdf9.5Nshn5lfEbQJF71eZgp86K"
```

I know it's a little more complicated, but certainly more accurate. Or the function names are not good.

**Comment by FalcoGer** [comment]
in other words: "$2a$13$" should not be part of the encoded salt string as it isn't part of the salt, and the hash you get out of HashPassword should not be called hash but digest, as the hash is only the last bit, not the salt or the modular crypt format identifier.

**Comment by ChrisMcKee** [comment]
> The salt for BCrypt is an array of 16 Bytes. The generateSalt function returns a string of 28 or 29 characters, of which 6 or 7 are workfactor and version number and $-delimiters, the rest is the actual salt, base64 encoded.

Legacy, backwards compatibility, it's just how its done; the codebase has been around a long time. If you read the readme file you'll see **I don't in anyway advocate managing your own salts in the first place** making this an internal method that's merely exposed as it's required by legacy.

The correct usage of this library is via the Hash/Verify and EnhancedHash etal which is all in the readme and available via intellisense.

The use of "generate salt" does, yes, contain the version and rounds; but as the library states and even includes a copy of the library it's based on https://github.com/jeremyh/jBCrypt/blob/master/src/main/java/org/mindrot/BCrypt.java#L714 this isn't a huge suprise. 
**It's also achieved in the same manner in the BSD bcrypt c code**
http://cvsweb.openbsd.org/cgi-bin/cvsweb/src/lib/libc/crypt/bcrypt.c?rev=1.57&content-type=text/x-cvsweb-markup

```
**static int
bcrypt_initsalt(int log_rounds, uint8_t *salt, size_t saltbuflen)
{
	uint8_t csalt[BCRYPT_MAXSALT];

	if (saltbuflen < BCRYPT_SALTSPACE) {
		errno = EINVAL;
		return -1;
	}

	arc4random_buf(csalt, sizeof(csalt));

	if (log_rounds < 4)
		log_rounds = 4;
	else if (log_rounds > 31)
		log_rounds = 31;

	snprintf(salt, saltbuflen, "$2b$%2.2u$", log_rounds);
	encode_base64(salt + 7, csalt, sizeof(csalt));

	return 0;
}
```

You'll also find the salt method returning in the same format (spring framework being another example https://docs.spring.io/spring-security/site/docs/4.2.10.RELEASE/apidocs/org/springframework/security/crypto/bcrypt/BCrypt.html / swift framework https://cocoapods.org/pods/BCryptSwift etc) in most other libraries; but again it's not really intended for direct consumption. There are few reasons to generate a salt via that method outside of testing. 

>why you would pass arguments like workfactor or version number to the generatehash function in the form of a string is confusing to me. giving the workfactor to the generatesalt function makes no sense. the generatesalt function doesn't use the workfactor.

"generate hash"? https://github.com/BcryptNet/bcrypt.net/blob/master/src/BCrypt.Net/BCrypt.cs 
No method matching that name; we have CryptRaw which takes bytes and HashPassword 

`the generatesalt function doesn't use the workfactor.`
No it doesn't but I covered that bit in the first section.

>in other words: "$2a$13$" should not be part of the encoded salt string as it isn't part of the salt, and the hash you get out of HashPassword should not be called hash but digest, as the hash is only the last bit, not the salt or the modular crypt format identifier.

As unbelievable as it is, I do have some idea what I'm doing; and if you had looked at the base code, or the many, many, other implementations 

Why do we use hash? because the fact that a digest is the output of a hash is of zero interest to 99.999% of people using the libraries... its also not used a term within other libraries. Comprehension is more important than being anal (ask anyone selling SSL certificates, most people give zero 💩 its an x.509 cert).
