### ISSUE TITLE
[Question] Use in production?

### ISSUE THREAD

**Issue by lonix1** [BcryptNet/bcrypt.net#35]
I need to port a node app to .net core and I need a bcrypt library. There are many available, but this one seems to be the most used. That said it's nowhere near as heavily used or reviewed as the node implementation, only has one maintainer, and hasn't undergone a review.

Is anyone using this in a "serious" production system? Any tips/advice to share?

*(Not trolling you @ChrisMcKee, I really appreciate the work you've done and am eager to use this... just need to tick some boxes first, you know how it is! :smile: And the framework doesn't have bcrypt built-in which is very sad!).*

**Comment by ChrisMcKee** [comment]
Yep it's used in a lot of large prod systems.
I can't really compare anything in nuget to npm as the nature of js/node inflates numbers.
Review wise ... I guess you haven't been using .net long, not exactly swimming in people writing posts on packages.

Code review wise the underlying code was from bcrypt 'official' which is a port of jbcrypt. They've both been poked by security Devs. But if you want to pay NCC a few grand I'm sure they'll review it 😉

**Comment by lonix1** [comment]
@ChrisMcKee I meant code review, not blogs etc. I had a manager who used to say "...but what if so and so would get hit by a bus?..." So I guess what I'm saying is I'd prefer not to waste all that money, but implore you to suitably look left and right every time you cross the road, please! :smile:

On a serious note, you might consider one of those "Used in production" / "Notable users" / whatever pages, to boast of actual deployments. Given that this is the only serious bcrypt implementation for .net, it would also be good publicity... just a friendly suggestion. If that page were available I'd have been embarrased to ask this question to begin with, thanks for not getting too upset about it. :wink:

**Comment by ChrisMcKee** [comment]
It's a common problem in oss. Testimonials using brands tends to be achieved by bribing in commercial settings or by the company being the creator or a big maintainer and wanting to advertise stuff. I can tell you a few by email 🤷🏻‍♂️

Code review wise paragons (Scott) had a poke (see prs) and the head of .net security (see FedEx timeout issue) I know both of these people. 
I've been writing .net since 2004, breaking shit a lot longer. 

I assume you mean security reviewed rather than code reviewed?
Getting code reviews is pretty easy, and it's had a fair few before GitHub and during. 
Security reviews are harder to get, but it's had a few, a nice commercial one to stick on the page would be good but there's no money trees near my house 😉

This basically fixed all of the holes in the 'official' library, I then extended it with new functionality (enhanced, which deals with the character limits in bcrypt), test coverage. 

Memberwise, yeahhhhhhh... That's awkward, I need to add some victims. Just OSS things 😂

**Comment by snekbaev** [comment]
You are doing a great job @ChrisMcKee :)

**Comment by ChrisMcKee** [comment]
Better start the cloning process

https://media.tenor.com/images/f7504d4fbffc7624f31e2aade44ba1ce/tenor.gif

**Comment by lonix1** [comment]
Wut... no money trees where you live? Pfft.

**Comment by ChrisMcKee** [comment]
Would be awesome
