### ISSUE TITLE
Upgrading to version 4.0 is a breaking change

### ISSUE THREAD

**Issue by harshmaurya** [BcryptNet/bcrypt.net#69]
I upgraded from 3.3.3 to 4.0 and it breaks the Bcrypt.EnhancedVerify method. Meaning the old hashes created by the 3.3.3 version cannot be verified by the new version. After I downgraded to the original version, my project started to work again. For hashing I use:

`Bcrypt.EnhancedHashPassword(plainPassword)`

I think this is a dangerous issue.

**Comment by ChrisMcKee** [comment]
The breaking change in v4 (semver major version / breaking-changes https://semver.org/#spec-item-8) was intentional to address a bug in Enhanced Hashing that causes the hashes created to be inoperable between different languages (PHP implementations / Go implementations & C#)

https://github.com/BcryptNet/bcrypt.net/tree/3.5.0 

3.5 contains all the same functionality, as well as the ability to migrate and I'll be backporting any changes to 3.x for a while. 

You can cap your packages to v3 if you require.
