### ISSUE TITLE
[Enhanced - V3/4] Is there a way to determine if a hash is v4 compatible or not?

### ISSUE THREAD

**Issue by junweilee** [BcryptNet/bcrypt.net#73]
With the breaking change in v4, I don't suppose there is a way to check if a hash was already v4 compatible other than to maintain it ourselves?

InterrogateHash will return the same version 2a regardless of the hash being from before 3.5 or after.

**Comment by ChrisMcKee** [comment]
The compatibility change only effects the "Enhanced Entropy"; if you're not using that its totally compatible.
If you are using that, no, the library has no way of tracking the difference as we've no viable option when it comes to altering the spec without breaking cross compatibility. 
Laziest way to handle the difference would be to use v3.5.0 (which has the additional v4CompatibleEnhancedEntropy flag) 
auth using v4 compatible; if/when fail validate using standard v3 logic; if valid at this point rehash against with v4 compatibility and store. (Laziest way because it reduces the need to manage state)
