### ISSUE TITLE
After Upgrade from v3.2.1 to v4 password is invalid

### ISSUE THREAD

**Issue by mschmeller** [BcryptNet/bcrypt.net#79]
Hello,
we did an NuGet package update to v4.0.2 for the .net 4.7.1 framework.
After that BCrypt.Net.BCrypt.EnhancedVerify returns false for an valid password.
We rolled back the package update to v3.2.1 and it worked as expected.

What's going wrong?

Best regard, Martin

**Comment by ChrisMcKee** [comment]
As per the release notes; 

v3.5.0 - A bug in Enhanced Hashing (before v3.5) was discovered that causes the hashes created to be inoperable between different languages. 
As part of the fix in v3.5, the ability to Verify and HashPassword were given an additional v4CompatibleEnhancedEntropy parameter. This allows the user to verify their Enhanced hash as normal; then re-hash + store using V4. This functionality is purely to allow migration and is removed in V4.

**The bug isn't a security issue**; its more an issue with how the API was intended to function and the cross compatibility between  this library and various java/php/go libs that contain similar implementations.

*If you want to migrate*
The easiest way to migrate the prior hashes is to store a flag against the user ~or~ set a before date check in the hash check based on the users auth records last modified. 

The laziest way / simplest way to handle the difference would be to use v3.5.0 (which has the additional v4CompatibleEnhancedEntropy flag); (Laziest way because it reduces the need to manage state)
* Authenticate the user using v4 compatible;
* if/when hash fails to validate using standard v3 logic
* if valid at this point rehash against with v4 compatibility and store.
